// 按需导入
import Vue from 'vue'
import { SwipeCell, Radio, RadioGroup, Cell, Tag, Empty, Popup, Form, Field, Switch, Area, Tab, Tabs, Checkbox, Dialog, ActionSheet, Rate, Icon, Search, Swipe, SwipeItem, Grid, GridItem, Button, Tabbar, TabbarItem, NavBar, Toast } from 'vant'
Vue.use(Button)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(NavBar)
Vue.use(Toast)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Icon)
Vue.use(Rate)
Vue.use(ActionSheet)
Vue.use(Dialog)
Vue.use(Checkbox)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Empty)
Vue.use(Popup)
Vue.use(Form)
Vue.use(Switch)
Vue.use(Area)
Vue.use(Field)
Vue.use(Tag)
Vue.use(Cell)
Vue.use(Radio)
Vue.use(RadioGroup)
Vue.use(SwipeCell)
